# Generated by Django 2.2 on 2019-04-05 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_center', models.CharField(max_length=50)),
                ('po_box', models.CharField(max_length=50)),
                ('telephone', models.IntegerField()),
                ('contact_person', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('physical_location', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
