# Generated by Django 2.2 on 2019-04-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('id_number', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('location', models.CharField(choices=[('Migori', 'Migori'), ('Homabay', 'Homabay'), ('Kisii', 'Kisii'), ('Awendo', 'Awendo')], max_length=50)),
                ('reason', models.CharField(choices=[('Depression', 'Depression'), ('Sexual Abuse', 'Sexual Abuse'), ('Gender Based Violence', 'Gender Based Violence'), ('Substance Abuse', 'Substance Abuse')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('date_posted', models.DateTimeField()),
            ],
        ),
    ]
